package cn.et.jurisdiction.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import cn.et.jurisdiction.entity.Emp;
import cn.et.jurisdiction.entity.EmpExample;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @SelectProvider(type=EmpSqlProvider.class, method="countByExample")
    long countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @DeleteProvider(type=EmpSqlProvider.class, method="deleteByExample")
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @Delete({
        "delete from emp",
        "where eid = #{eid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @Insert({
        "insert into emp (eid, ename, ",
        "sal, did)",
        "values (#{eid,jdbcType=INTEGER}, #{ename,jdbcType=VARCHAR}, ",
        "#{sal,jdbcType=INTEGER}, #{did,jdbcType=INTEGER})"
    })
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @InsertProvider(type=EmpSqlProvider.class, method="insertSelective")
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @SelectProvider(type=EmpSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="eid", property="eid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ename", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="sal", property="sal", jdbcType=JdbcType.INTEGER),
        @Result(column="did", property="did", jdbcType=JdbcType.INTEGER)
    })
    List<Emp> selectByExampleWithRowbounds(EmpExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @SelectProvider(type=EmpSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="eid", property="eid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ename", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="sal", property="sal", jdbcType=JdbcType.INTEGER),
        @Result(column="did", property="did", jdbcType=JdbcType.INTEGER)
    })
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @Select({
        "select",
        "eid, ename, sal, did",
        "from emp",
        "where eid = #{eid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="eid", property="eid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ename", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="sal", property="sal", jdbcType=JdbcType.INTEGER),
        @Result(column="did", property="did", jdbcType=JdbcType.INTEGER)
    })
    Emp selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @UpdateProvider(type=EmpSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @UpdateProvider(type=EmpSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @UpdateProvider(type=EmpSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 13 20:01:16 CST 2017
     */
    @Update({
        "update emp",
        "set ename = #{ename,jdbcType=VARCHAR},",
          "sal = #{sal,jdbcType=INTEGER},",
          "did = #{did,jdbcType=INTEGER}",
        "where eid = #{eid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Emp record);
}