package cn.et.jurisdiction.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import cn.et.jurisdiction.entity.Student;
import cn.et.jurisdiction.entity.StudentExample;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @SelectProvider(type=StudentSqlProvider.class, method="countByExample")
    Integer countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @DeleteProvider(type=StudentSqlProvider.class, method="deleteByExample")
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @Delete({
        "delete from student",
        "where stuid = #{stuid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer stuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @Insert({
        "insert into student (stuid, stuname, ",
        "stusex, stuage, ",
        "bordate, picture)",
        "values (#{stuid,jdbcType=INTEGER}, #{stuname,jdbcType=VARCHAR}, ",
        "#{stusex,jdbcType=VARCHAR}, #{stuage,jdbcType=INTEGER}, ",
        "#{bordate,jdbcType=TIMESTAMP}, #{picture,jdbcType=VARCHAR})"
    })
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @InsertProvider(type=StudentSqlProvider.class, method="insertSelective")
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @SelectProvider(type=StudentSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="stuid", property="stuid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="stuname", property="stuname", jdbcType=JdbcType.VARCHAR),
        @Result(column="stusex", property="stusex", jdbcType=JdbcType.VARCHAR),
        @Result(column="stuage", property="stuage", jdbcType=JdbcType.INTEGER),
        @Result(column="bordate", property="bordate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR)
    })
    List<Student> selectByExampleWithRowbounds(StudentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @SelectProvider(type=StudentSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="stuid", property="stuid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="stuname", property="stuname", jdbcType=JdbcType.VARCHAR),
        @Result(column="stusex", property="stusex", jdbcType=JdbcType.VARCHAR),
        @Result(column="stuage", property="stuage", jdbcType=JdbcType.INTEGER),
        @Result(column="bordate", property="bordate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR)
    })
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @Select({
        "select",
        "stuid, stuname, stusex, stuage, bordate, picture",
        "from student",
        "where stuid = #{stuid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="stuid", property="stuid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="stuname", property="stuname", jdbcType=JdbcType.VARCHAR),
        @Result(column="stusex", property="stusex", jdbcType=JdbcType.VARCHAR),
        @Result(column="stuage", property="stuage", jdbcType=JdbcType.INTEGER),
        @Result(column="bordate", property="bordate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR)
    })
    Student selectByPrimaryKey(Integer stuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @UpdateProvider(type=StudentSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @UpdateProvider(type=StudentSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @UpdateProvider(type=StudentSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    @Update({
        "update student",
        "set stuname = #{stuname,jdbcType=VARCHAR},",
          "stusex = #{stusex,jdbcType=VARCHAR},",
          "stuage = #{stuage,jdbcType=INTEGER},",
          "bordate = #{bordate,jdbcType=TIMESTAMP},",
          "picture = #{picture,jdbcType=VARCHAR}",
        "where stuid = #{stuid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Student record);
}