package cn.et.jurisdiction.entity;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuid
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    private Integer stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuname
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    private String stuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stusex
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    private String stusex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuage
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    private Integer stuage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bordate
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    private Date bordate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.picture
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuid
     *
     * @return the value of student.stuid
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public Integer getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuid
     *
     * @param stuid the value for student.stuid
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public void setStuid(Integer stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuname
     *
     * @return the value of student.stuname
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuname
     *
     * @param stuname the value for student.stuname
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stusex
     *
     * @return the value of student.stusex
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public String getStusex() {
        return stusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stusex
     *
     * @param stusex the value for student.stusex
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public void setStusex(String stusex) {
        this.stusex = stusex == null ? null : stusex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuage
     *
     * @return the value of student.stuage
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public Integer getStuage() {
        return stuage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuage
     *
     * @param stuage the value for student.stuage
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public void setStuage(Integer stuage) {
        this.stuage = stuage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bordate
     *
     * @return the value of student.bordate
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public Date getBordate() {
        return bordate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bordate
     *
     * @param bordate the value for student.bordate
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public void setBordate(Date bordate) {
        this.bordate = bordate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.picture
     *
     * @return the value of student.picture
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.picture
     *
     * @param picture the value for student.picture
     *
     * @mbg.generated Tue Dec 12 09:29:57 CST 2017
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

	@Override
	public String toString() {
		return "Student [stuid=" + stuid + ", stuname=" + stuname + ", stusex=" + stusex + ", stuage=" + stuage
				+ ", bordate=" + bordate + ", picture=" + picture + "]";
	}
    
    
}